### ISSUE TITLE
updating the code for more recent THREE versions

### ISSUE THREAD

**Issue by dhk-room101** [jeromeetienne/threex.volumetricspotlight#2]
hi, I was testing your volumetric spotlight class, and although it works as intended for THREE 59, I also tested it with THREE 62, 69, 70. For THREE 62, the result was somewhat functional, in the sense that the spotlight cylinder was being displayed, but the segments of the cylinder were too obvious. For THREE 69/70 nothing was being displayed.

 I was wondering if you would be willing to update this class to work with THREE 70. I can also give it a try, if you point me in the right direction

 Thanks!

**Comment by jeromeetienne** [comment]
i just ported to three.js r71. sorry for the delay

This was just small incompatibilities in the demos.

**Comment by jeromeetienne** [comment]
thanks weiserhei for pinging/arrassing me on irc :)

**Comment by mobbjelly** [comment]
Hi, update for the three.js r108 version?
